version: '3.9'
services:
  ms-dyssomnia-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
    networks:
      - dyssomnia-network
    deploy:
      replicas: 1

networks:
  dyssomnia-network:
    external: true
